services:
  - type: web
    name: advocate-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_ORIGIN
        value: https://advocate-client.onrender.com
      - key: DATABASE_URL
        value: "" # set your PostgreSQL connection string in the Render dashboard
      - key: DATABASE_SSL
        value: "true" # set to true if your provider requires SSL (e.g., Render/Neon/Supabase)

  - type: static
    name: advocate-client
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SOCKET_URL
        fromService:
          type: web
          name: advocate-backend
          envVarKey: RENDER_EXTERNAL_URL
